name: Restore build cache
description: Restore build cache.
inputs:
  cache-name:
    description: The cache base name (job name by default).
    default: ${{ github.job }}
  cache-path:
    description: The cache path.
    default: ${{ github.workspace }}/.cache/
  branch-name:
    description: The GitHub branch name (ref_name by default).
    default: ${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: Restore build cache directory
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-name }}-${{ inputs.branch-name }}-${{ github.sha }}

        restore-keys: |
          ${{ inputs.cache-name }}-${{ inputs.branch-name }}