include "Thirdparty/glad"
include "Thirdparty/premake-glfw.lua"
include "Thirdparty/premake-glslang.lua"
include "Thirdparty/premake-SPIRV-Cross.lua"
include "Thirdparty/stb"
include "Thirdparty/premake-box2d.lua"