name: build

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config: [debug, release, dist]
        platform: [x64]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-11 gcc-11 libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxxf86vm-dev mesa-common-dev
      
    - name: Build ${{ matrix.platform }} ${{ matrix.config }}
      run: |
        chmod u+r+x Tools/Linux/premake5
        Tools/Linux/premake5 gmake2
        make config=${{ matrix.config }} CC=gcc-11 CXX=g++-11 -j8

    - name: Upload Bin Artifacts
      uses: ./.github/actions/upload-artifact
      with:
        name: Koten-Linux-${{ matrix.config }}-${{ matrix.platform }}
        path: bin
  
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release, Dist]
        platform: [x64]
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Generate Project
      shell: cmd
      run: | 
        cd Scripts/Windows
        GenVS22.bat

    - name: Build ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd
      run: |
        "%MSBUILD_PATH%\MSBuild.exe" /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.config }} Koten.sln

    - name: Upload Bin Artifacts
      uses: ./.github/actions/upload-artifact
      with:
        name: "Koten-Windows-${{ matrix.config }}-${{ matrix.platform }}"
        path: "bin"

  CleanUp:
    runs-on: ubuntu-latest
    needs: [Linux, Windows]
    steps:
      - name: Delete All Caches
        run: |
          echo "Fetching list of cache keys..."
          cacheKeys=$(gh cache list --limit 100 --json id --jq '.[].id')

          if [ -z "$cacheKeys" ]; then
            echo "No caches found. Skipping cleanup."
            exit 0
          fi

          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh cache delete $cacheKey
          done
          echo "Cleanup complete."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}