name: Windows

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release, Dist]
        platform: [x64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Show MSBuild
        shell: cmd
        run: |
          where msbuild
          msbuild -version

      - name: Generate Project
        shell: cmd
        run: |
          GenVS22.bat

      - name: Verify Solution
        shell: cmd
        run: |
          dir *.sln

      - name: Build ${{ matrix.platform }} ${{ matrix.config }}
        shell: cmd
        run: |
          msbuild Koten.sln ^
            /m ^
            /p:Platform=${{ matrix.platform }} ^
            /p:Configuration=${{ matrix.config }}

      - name: Upload Bin Artifacts
        uses: ./.github/actions/upload-artifact
        with:
          name: Koten-Windows-${{ matrix.config }}-${{ matrix.platform }}
          path: bin