name: windows

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release, Dist]
        platform: [x64]
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Generate Project
      shell: cmd
      run: | 
        GenVS22.bat

    - name: Build ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd
      run: |
        "%MSBUILD_PATH%\MSBuild.exe" /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.config }} Koten.sln

    - name: Upload Bin Artifacts
      uses: ./.github/actions/upload-artifact
      with:
        name: "Koten-Windows-${{ matrix.config }}-${{ matrix.platform }}"
        path: "bin"
